### ISSUE TITLE
How to handle external vocabularies in RECO?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#113] opened 2021-06-15 09:10 UTC
Hi all and especially @neil-ices-dk, @mehdiabbasi, @cekv, @Osanna123, @pcrjoana), 

I know we have touched this subject in last vocab meeting where @mehdiabbasi and I was present but I don't think we discussed it fully after all as our focus was slighly different which is why I take it up again.
 
I just had a discussion on this with first @cekv and then @mehdiabbasi on how to handle external vocabularies like WoRMS, P01 etc. in RECO.

In my point of view we should display all acceptable codes in the RECO interface for all vocabularies including external vocabularies!

For a vocabulary like WoRMS and possible P01 this would requere a 1:1 synchronisation of accepted codes like is done for EDMO.

If we don't do a 1:1 synchronisation then the indivdual systems in ICES will need to direct our users towards where the external vocabularies are manage and then create a web service for each vocabulary which will insert codes accepted externally but not in RECO which kind of defeat the purpose of having these vocabularies in RECO in the first place.  

For external list like ISO_3166 I think it makes sense to have a subset of this allready mixed vocabulary as these codes are the ones acually accepted by ICES.

I don't think the argument of RECO only having codes used in ICES datasets makes sense, partly because it doen't help our users trying to submit new data into a given dataset, and partly because I seem to understand that several systems allready are bending this rule, if that's the argument for having subsets.

Regarding the number of codes in RECO which the 1:1 synchonisation of the rather big vocabularies of what's accepted codes, then database wise that's not an issue at all, and looking at the interfaces around which makes use of these list, there are many intelligent ways to handle big lists like these which can both be performant and intuitive for the users as well i.e. you can as an example start typing and when 2 or 3 letters or so have been reached then a lookup will be made - or the like.

Thanks for your consideration.

P.S. We allready have a solution for 1:1 synchronisation in place in RECO which will be piece of cake to use for other external lists

**Comment by mehdiabbasi** [comment] 2021-06-15 09:19
Technically we have already a solution for sync the full list and I will implement also web service for the sync subset soon, so both are possible. I just want to mention, full worms list is around 1.3 million records. of course, this is nothing for SQL, but for RECO webpage that is the old asp.net page, can cause some slowness.

**Comment by neil-ices-dk** [comment] 2021-06-15 09:43
as we discussed previously, the main technical barrier is not around handling alot of records, but making it easy for the user to find the codes they need - which i'm not sure we have in hand at the moment and if we look to BODC vocabs it is something that they haven't really come up with an intuitive solution for. So i agree in essence with the sentiment - that we serve a like for like list, but we need some more thought on how we help the user find the needle in the haystack - which might need some additional effort that would need to be planned.

**Comment by HjalteParner** [comment] 2021-06-15 09:46
@neil-ices-dk I fully agree

**Comment by Osanna123** [comment] 2021-06-16 12:29
@HjalteParner you forgot to add the project. is it DIG or RMG related?

**Comment by Osanna123** [comment] 2021-06-16 12:30
Duplicate of https://github.com/ices-eg/DIG/issues/101

**Closed by Osanna123** 2021-06-16 12:30 UTC
