### ISSUE TITLE
RDBES: RS_incidentialByCatchMitigateDev update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#159] opened 2021-08-04 12:09 UTC
Please see attached spreadsheet for the 22 code updates.

[RS_incidentialByCatchMitigateDev updates.xlsx](https://github.com/ices-eg/DIG/files/6931075/RS_incidentialByCatchMitigateDev.updates.xlsx)

**Comment by cekv** [comment] 2021-08-09 14:51
Existing codetype : https://vocab.ices.dk/?ref=1613

**Comment by HenrikK-N** [comment] 2021-08-10 06:27
Please write one sentence of why you give the reference the existing codes. I think the reference is because there is an issue with 2 of the referred existing codes in the requested spreadsheet, that are not exactly the same, existing: FuncADD (referred: Funcping) and existing: Excl (referred: Sealexcl). Please see the updated spreadsheet.

[RS_incidentialByCatchMitigateDev updates 159.xlsx](https://github.com/ices-eg/DIG/files/6959419/RS_incidentialByCatchMitigateDev.updates.159.xlsx)

**Comment by cekv** [comment] 2021-08-11 12:14
Duplicate of #107

**Comment by HenrikK-N** [comment] 2021-08-11 14:50
It is not a duplicate of #107 RS_IncidentalByCatchMitigationDevTarget
107 are the '...Target'
Codes are e.g. 

---
SmallCetaceans
LargeCetaceans
ProtectedElasmobranchs
Birds
Turtles
---
This #159 is the device '....Dev' codes like ModHook, AttAltProf...

**Comment by cekv** [comment] 2021-08-12 09:54
As suggested in issue #107 naming it BycatchMitigationDevice

**Closed** 2021-08-13 14:19 UTC
Labels: Approved-WithChanges, vocab: CodeValue, vocab: new, vocab: concept change
